### ISSUE TITLE
Document running lnmux in docker

### ISSUE THREAD

**Issue by joostjager** [NYDIG-OSS/lnmux#40]
PR #38 added a docker build. What might be useful is a description of how to run lnmux in docker via the command line.

**Comment by Torakushi** [comment]
Good idea, it could be nice to have a dev.Dockerfile like in LND (this docker will copy the lnmux.yml found in the folder and launch lnmux with this config)

I don't think that changing the actual Dockerfile is a good idea, since people may use chart and override entrypoint to inject their config. (and we don't want conflicts)

It could be good to add a docker-compose maybe to create the postgres DB as well?

What do you think?

**Comment by Torakushi** [comment]
Good idea, we can use this PR to fix the documentation (README) as well.

I can do that, I may have some time next week
